name: transcripcion
channels:
  - conda-forge
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - aom=3.9.1
  - backports.zstd=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - cpython=3.10.19
  - dav1d=1.2.1
  - dbus=1.16.2
  - ffmpeg=8.0.0
  - filelock=3.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - giflib=5.2.2
  - glslang=16.1.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h2=4.3.0
  - harfbuzz=12.2.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - jinja2=3.1.6
  - lame=3.100
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libass=0.17.4
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcxx=21.1.7
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.3
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenvino=2025.2.0
  - libopenvino-arm-cpu-plugin=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.5.2
  - libpng=1.6.53
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsqlite=3.51.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp=1.6.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=3.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.6
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pango=1.56.4
  - pcre2=10.47
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - pysocks=1.7.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.5.1
  - pyyaml=6.0.3
  - readline=8.2
  - requests=2.32.5
  - sdl2=2.32.56
  - sdl3=3.2.28
  - setuptools=80.9.0
  - shaderc=2025.4
  - snappy=1.2.2
  - spirv-tools=2025.4
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.1
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zlib-ng=2.3.2
  - zstd=1.5.7
  - pip:
    - HyperPyYAML==1.2.2
    - Mako==1.3.10
    - Pygments==2.19.2
    - SQLAlchemy==2.0.45
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - alembic==1.17.2
    - antlr4-python3-runtime==4.9.3
    - asteroid-filterbanks==0.4.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - av==15.1.0
    - cffi==2.0.0
    - click==8.3.1
    - coloredlogs==15.0.1
    - colorlog==6.10.1
    - contourpy==1.3.2
    - ctranslate2==4.6.2
    - cycler==0.12.1
    - docopt==0.6.2
    - einops==0.8.1
    - faster-whisper==1.2.1
    - flatbuffers==25.9.23
    - fonttools==4.61.1
    - frozenlist==1.8.0
    - fsspec==2025.12.0
    - hf-xet==1.2.0
    - huggingface-hub==0.36.0
    - humanfriendly==10.0
    - joblib==1.5.2
    - julius==0.2.7
    - kiwisolver==1.4.9
    - lightning==2.6.0
    - lightning-utilities==0.15.2
    - markdown-it-py==4.0.0
    - matplotlib==3.10.8
    - mdurl==0.1.2
    - multidict==6.7.0
    - nltk==3.9.2
    - numpy==2.0.2
    - omegaconf==2.3.0
    - onnxruntime==1.23.2
    - optuna==4.6.0
    - packaging==25.0
    - pandas==2.2.3
    - primePy==1.3
    - propcache==0.4.1
    - protobuf==6.33.2
    - pyannote.audio==3.4.0
    - pyannote.core==5.0.0
    - pyannote.database==5.1.3
    - pyannote.metrics==3.2.1
    - pyannote.pipeline==3.0.1
    - pycparser==2.23
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytorch-lightning==2.6.0
    - pytorch-metric-learning==2.9.0
    - pytz==2025.2
    - regex==2025.11.3
    - rich==14.2.0
    - ruamel.yaml==0.18.16
    - ruamel.yaml.clib==0.2.15
    - safetensors==0.7.0
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - semver==3.0.4
    - sentencepiece==0.2.1
    - shellingham==1.5.4
    - six==1.17.0
    - sortedcontainers==2.4.0
    - soundfile==0.13.1
    - speechbrain==1.0.3
    - tabulate==0.9.0
    - tensorboardX==2.6.4
    - threadpoolctl==3.6.0
    - tokenizers==0.21.4
    - tomli==2.3.0
    - torch-audiomentations==0.12.0
    - torch_pitch_shift==1.2.5
    - torchmetrics==1.8.2
    - tqdm==4.67.1
    - transformers==4.48.0
    - typer==0.20.0
    - tzdata==2025.3
    - whisperx==3.7.4
    - yarl==1.22.0


